name: Nightly

on:
  workflow_dispatch:

jobs:
  link-checks:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          fail: false
      - name: Create Issues
        if: steps.lychee.outputs.exit_code != '0'
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: 1
          body-path: ./lychee/out.md
      - name: Fail on Issues
        if: steps.lychee.outputs.exit_code != '0'
        run: |
          echo "Link Checker found issues. Please check the created issue for details."
          exit 1
